declare class process {
  static env: {
    REACT_APP_API_URL: string,
    REACT_APP_MICROSOFT_URL: string,
    REACT_APP_CLIENT_ID: string,
    REACT_APP_TENANT_URL: string,
    REACT_APP_REDIRECT_URL: string,
    REACT_APP_MAPBOX_TOKEN: string,
    REACT_APP_FEATURE_FLAGS: string,
    REACT_APP_FIREBASE_API_KEY: string,
    REACT_APP_FIREBASE_AUTH_DOMAIN: string,
    REACT_APP_FIREBASE_DATABASE_URL: string,
    REACT_APP_FIREBASE_PROJECT_ID: string,
    REACT_APP_FIREBASE_STORAGE_BUCKET: string,
    REACT_APP_FIREBASE_SENDER_ID: string,
    REACT_APP_FIREBASE_APP_ID: string,
    REACT_APP_FIREBASE_MEASUREMENT_ID: string,
    REACT_APP_FIREBASE_PUBLIC_API_KEY: string
  };
}
