// flow-typed signature: 2a3c6857ee0c9cae37723c648f01d170
// flow-typed version: <<STUB>>/@types/material-ui_v^0.21.7/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/material-ui' {
  declare module.exports: any;
}
