// flow-typed signature: 1ca0923d37d3cc7a8f082120b827715c
// flow-typed version: <<STUB>>/hellosign-embedded_v^2.8.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hellosign-embedded'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hellosign-embedded' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hellosign-embedded/umd/embedded.development' {
  declare module.exports: any;
}

declare module 'hellosign-embedded/umd/embedded.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hellosign-embedded/index' {
  declare module.exports: $Exports<'hellosign-embedded'>;
}
declare module 'hellosign-embedded/index.js' {
  declare module.exports: $Exports<'hellosign-embedded'>;
}
declare module 'hellosign-embedded/umd/embedded.development.js' {
  declare module.exports: $Exports<'hellosign-embedded/umd/embedded.development'>;
}
declare module 'hellosign-embedded/umd/embedded.production.min.js' {
  declare module.exports: $Exports<'hellosign-embedded/umd/embedded.production.min'>;
}
