// flow-typed signature: ae8d6bd9a6daa0ee0d3131b6e1bf5439
// flow-typed version: <<STUB>>/html2canvas_v^1.0.0-rc.7/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html2canvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html2canvas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html2canvas/dist/html2canvas.esm' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/html2canvas' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/html2canvas.min' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/__tests__' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/__mocks__/cache-storage' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/__mocks__/features' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/__mocks__/logger' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/__tests__/cache-storage' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/__tests__/logger' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/bitwise' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/cache-storage' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/features' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/logger' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/core/util' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/IPropertyDescriptor' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/ITypeDescriptor' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/layout/__mocks__/bounds' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/layout/bounds' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/layout/text' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/background-tests' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/font-family' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/text-shadow' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/transform-tests' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-clip' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-color' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-image' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-origin' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-position' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-repeat' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/background-size' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/border-color' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/border-radius' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/border-style' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/border-width' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/box-shadow' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/color' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/content' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/counter-increment' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/counter-reset' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/display' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/float' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/font-family' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/font-size' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/font-style' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/font-variant' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/font-weight' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/letter-spacing' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/line-break' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/line-height' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/list-style-image' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/list-style-position' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/list-style-type' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/margin' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/opacity' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/overflow-wrap' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/overflow' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/padding' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/position' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/quotes' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/text-align' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/text-decoration-color' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/text-decoration-line' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/text-shadow' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/text-transform' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/transform-origin' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/transform' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/visibility' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/word-break' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/property-descriptors/z-index' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/syntax/__tests__/tokernizer-tests' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/syntax/parser' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/syntax/tokenizer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/__tests__/color-tests' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/__tests__/image-tests' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/angle' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/color' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/__tests__/radial-gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/-prefix-linear-gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/-prefix-radial-gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/-webkit-gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/counter' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/linear-gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/functions/radial-gradient' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/image' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/length-percentage' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/css/types/length' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/__mocks__/document-cloner' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/document-cloner' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/elements/li-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/elements/ol-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/elements/select-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/elements/textarea-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/node-parser' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements/canvas-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements/iframe-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements/image-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements/input-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements/pseudo-elements' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/replaced-elements/svg-element-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/dom/text-container' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/invariant' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/background' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/bezier-curve' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/border' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/bound-curves' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/box-sizing' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/canvas/canvas-renderer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/canvas/foreignobject-renderer' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/effects' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/font-metrics' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/path' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/stacking-context' {
  declare module.exports: any;
}

declare module 'html2canvas/dist/lib/render/vector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html2canvas/dist/html2canvas.esm.js' {
  declare module.exports: $Exports<'html2canvas/dist/html2canvas.esm'>;
}
declare module 'html2canvas/dist/html2canvas.js' {
  declare module.exports: $Exports<'html2canvas/dist/html2canvas'>;
}
declare module 'html2canvas/dist/html2canvas.min.js' {
  declare module.exports: $Exports<'html2canvas/dist/html2canvas.min'>;
}
declare module 'html2canvas/dist/lib/__tests__/index' {
  declare module.exports: $Exports<'html2canvas/dist/lib/__tests__'>;
}
declare module 'html2canvas/dist/lib/__tests__/index.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/__tests__'>;
}
declare module 'html2canvas/dist/lib/core/__mocks__/cache-storage.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/__mocks__/cache-storage'>;
}
declare module 'html2canvas/dist/lib/core/__mocks__/features.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/__mocks__/features'>;
}
declare module 'html2canvas/dist/lib/core/__mocks__/logger.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/__mocks__/logger'>;
}
declare module 'html2canvas/dist/lib/core/__tests__/cache-storage.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/__tests__/cache-storage'>;
}
declare module 'html2canvas/dist/lib/core/__tests__/logger.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/__tests__/logger'>;
}
declare module 'html2canvas/dist/lib/core/bitwise.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/bitwise'>;
}
declare module 'html2canvas/dist/lib/core/cache-storage.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/cache-storage'>;
}
declare module 'html2canvas/dist/lib/core/features.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/features'>;
}
declare module 'html2canvas/dist/lib/core/logger.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/logger'>;
}
declare module 'html2canvas/dist/lib/core/util.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/core/util'>;
}
declare module 'html2canvas/dist/lib/css/index' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css'>;
}
declare module 'html2canvas/dist/lib/css/index.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css'>;
}
declare module 'html2canvas/dist/lib/css/IPropertyDescriptor.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/IPropertyDescriptor'>;
}
declare module 'html2canvas/dist/lib/css/ITypeDescriptor.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/ITypeDescriptor'>;
}
declare module 'html2canvas/dist/lib/css/layout/__mocks__/bounds.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/layout/__mocks__/bounds'>;
}
declare module 'html2canvas/dist/lib/css/layout/bounds.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/layout/bounds'>;
}
declare module 'html2canvas/dist/lib/css/layout/text.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/layout/text'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/background-tests.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/__tests__/background-tests'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/font-family.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/__tests__/font-family'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/text-shadow.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/__tests__/text-shadow'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/__tests__/transform-tests.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/__tests__/transform-tests'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-clip.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-clip'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-color.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-color'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-image.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-image'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-origin.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-origin'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-position.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-position'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-repeat.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-repeat'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/background-size.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/background-size'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/border-color.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/border-color'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/border-radius.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/border-radius'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/border-style.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/border-style'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/border-width.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/border-width'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/box-shadow.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/box-shadow'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/color.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/color'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/content.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/content'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/counter-increment.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/counter-increment'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/counter-reset.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/counter-reset'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/display.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/display'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/float.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/float'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/font-family.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/font-family'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/font-size.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/font-size'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/font-style.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/font-style'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/font-variant.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/font-variant'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/font-weight.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/font-weight'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/letter-spacing.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/letter-spacing'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/line-break.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/line-break'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/line-height.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/line-height'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/list-style-image.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/list-style-image'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/list-style-position.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/list-style-position'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/list-style-type.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/list-style-type'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/margin.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/margin'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/opacity.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/opacity'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/overflow-wrap.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/overflow-wrap'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/overflow.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/overflow'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/padding.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/padding'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/position.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/position'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/quotes.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/quotes'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/text-align.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/text-align'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/text-decoration-color.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/text-decoration-color'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/text-decoration-line.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/text-decoration-line'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/text-shadow.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/text-shadow'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/text-transform.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/text-transform'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/transform-origin.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/transform-origin'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/transform.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/transform'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/visibility.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/visibility'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/word-break.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/word-break'>;
}
declare module 'html2canvas/dist/lib/css/property-descriptors/z-index.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/property-descriptors/z-index'>;
}
declare module 'html2canvas/dist/lib/css/syntax/__tests__/tokernizer-tests.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/syntax/__tests__/tokernizer-tests'>;
}
declare module 'html2canvas/dist/lib/css/syntax/parser.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/syntax/parser'>;
}
declare module 'html2canvas/dist/lib/css/syntax/tokenizer.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/syntax/tokenizer'>;
}
declare module 'html2canvas/dist/lib/css/types/__tests__/color-tests.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/__tests__/color-tests'>;
}
declare module 'html2canvas/dist/lib/css/types/__tests__/image-tests.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/__tests__/image-tests'>;
}
declare module 'html2canvas/dist/lib/css/types/angle.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/angle'>;
}
declare module 'html2canvas/dist/lib/css/types/color.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/color'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/__tests__/radial-gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/__tests__/radial-gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/-prefix-linear-gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/-prefix-linear-gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/-prefix-radial-gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/-prefix-radial-gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/-webkit-gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/-webkit-gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/counter.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/counter'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/linear-gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/linear-gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/functions/radial-gradient.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/functions/radial-gradient'>;
}
declare module 'html2canvas/dist/lib/css/types/image.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/image'>;
}
declare module 'html2canvas/dist/lib/css/types/index' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types'>;
}
declare module 'html2canvas/dist/lib/css/types/index.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types'>;
}
declare module 'html2canvas/dist/lib/css/types/length-percentage.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/length-percentage'>;
}
declare module 'html2canvas/dist/lib/css/types/length.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/css/types/length'>;
}
declare module 'html2canvas/dist/lib/dom/__mocks__/document-cloner.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/__mocks__/document-cloner'>;
}
declare module 'html2canvas/dist/lib/dom/document-cloner.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/document-cloner'>;
}
declare module 'html2canvas/dist/lib/dom/element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/element-container'>;
}
declare module 'html2canvas/dist/lib/dom/elements/li-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/elements/li-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/elements/ol-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/elements/ol-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/elements/select-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/elements/select-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/elements/textarea-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/elements/textarea-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/node-parser.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/node-parser'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/canvas-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements/canvas-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/iframe-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements/iframe-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/image-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements/image-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/index' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/index.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/input-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements/input-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/pseudo-elements.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements/pseudo-elements'>;
}
declare module 'html2canvas/dist/lib/dom/replaced-elements/svg-element-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/replaced-elements/svg-element-container'>;
}
declare module 'html2canvas/dist/lib/dom/text-container.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/dom/text-container'>;
}
declare module 'html2canvas/dist/lib/index' {
  declare module.exports: $Exports<'html2canvas/dist/lib'>;
}
declare module 'html2canvas/dist/lib/index.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib'>;
}
declare module 'html2canvas/dist/lib/invariant.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/invariant'>;
}
declare module 'html2canvas/dist/lib/render/background.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/background'>;
}
declare module 'html2canvas/dist/lib/render/bezier-curve.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/bezier-curve'>;
}
declare module 'html2canvas/dist/lib/render/border.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/border'>;
}
declare module 'html2canvas/dist/lib/render/bound-curves.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/bound-curves'>;
}
declare module 'html2canvas/dist/lib/render/box-sizing.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/box-sizing'>;
}
declare module 'html2canvas/dist/lib/render/canvas/canvas-renderer.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/canvas/canvas-renderer'>;
}
declare module 'html2canvas/dist/lib/render/canvas/foreignobject-renderer.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/canvas/foreignobject-renderer'>;
}
declare module 'html2canvas/dist/lib/render/effects.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/effects'>;
}
declare module 'html2canvas/dist/lib/render/font-metrics.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/font-metrics'>;
}
declare module 'html2canvas/dist/lib/render/path.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/path'>;
}
declare module 'html2canvas/dist/lib/render/stacking-context.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/stacking-context'>;
}
declare module 'html2canvas/dist/lib/render/vector.js' {
  declare module.exports: $Exports<'html2canvas/dist/lib/render/vector'>;
}
