// flow-typed signature: 2292ceb9af5d52b984706838574a961b
// flow-typed version: <<STUB>>/imutable_v0.0.1/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imutable/lib/imutable' {
  declare module.exports: any;
}

declare module 'imutable/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imutable/lib/imutable.js' {
  declare module.exports: $Exports<'imutable/lib/imutable'>;
}
declare module 'imutable/lib/index' {
  declare module.exports: $Exports<'imutable/lib'>;
}
declare module 'imutable/lib/index.js' {
  declare module.exports: $Exports<'imutable/lib'>;
}
