// flow-typed signature: e86c502b524807de118559bec8c28c39
// flow-typed version: <<STUB>>/mui-datatables_v^2.15.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mui-datatables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mui-datatables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mui-datatables/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mui-datatables/dist/index' {
  declare module.exports: $Exports<'mui-datatables/dist'>;
}
declare module 'mui-datatables/dist/index.js' {
  declare module.exports: $Exports<'mui-datatables/dist'>;
}
