// flow-typed signature: 4308754d4752aacf2ec88a9a267ea987
// flow-typed version: <<STUB>>/notistack_v^0.9.11/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notistack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notistack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notistack/dist' {
  declare module.exports: any;
}

declare module 'notistack/dist/notistack.cjs.development' {
  declare module.exports: any;
}

declare module 'notistack/dist/notistack.cjs.production.min' {
  declare module.exports: any;
}

declare module 'notistack/dist/notistack.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notistack/dist/index' {
  declare module.exports: $Exports<'notistack/dist'>;
}
declare module 'notistack/dist/index.js' {
  declare module.exports: $Exports<'notistack/dist'>;
}
declare module 'notistack/dist/notistack.cjs.development.js' {
  declare module.exports: $Exports<'notistack/dist/notistack.cjs.development'>;
}
declare module 'notistack/dist/notistack.cjs.production.min.js' {
  declare module.exports: $Exports<'notistack/dist/notistack.cjs.production.min'>;
}
declare module 'notistack/dist/notistack.esm.js' {
  declare module.exports: $Exports<'notistack/dist/notistack.esm'>;
}
