// flow-typed signature: e5da4983dee42cfdb5f82d531ae5a0a3
// flow-typed version: <<STUB>>/npm_v^8.3.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm/bin/npm-cli' {
  declare module.exports: any;
}

declare module 'npm/bin/npx-cli' {
  declare module.exports: any;
}

declare module 'npm/lib/arborist-cmd' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/legacy' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/oauth' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/saml' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/sso' {
  declare module.exports: any;
}

declare module 'npm/lib/base-command' {
  declare module.exports: any;
}

declare module 'npm/lib/cli' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/access' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/adduser' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/audit' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/bin' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/birthday' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/bugs' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/cache' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/ci' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/completion' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/config' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/dedupe' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/deprecate' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/diff' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/dist-tag' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/docs' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/doctor' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/edit' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/exec' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/explain' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/explore' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/find-dupes' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/fund' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/get' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/help-search' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/help' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/hook' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/init' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/install-ci-test' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/install-test' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/install' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/link' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/ll' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/logout' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/ls' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/org' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/outdated' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/owner' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/pack' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/ping' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/pkg' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/profile' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/prune' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/publish' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/rebuild' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/repo' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/restart' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/root' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/run-script' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/search' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/set-script' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/set' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/star' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/stars' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/start' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/stop' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/team' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/test' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/token' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/uninstall' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/unpublish' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/unstar' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/update' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/version' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/view' {
  declare module.exports: any;
}

declare module 'npm/lib/commands/whoami' {
  declare module.exports: any;
}

declare module 'npm/lib/exec/get-workspace-location-msg' {
  declare module.exports: any;
}

declare module 'npm/lib/lifecycle-cmd' {
  declare module.exports: any;
}

declare module 'npm/lib/npm' {
  declare module.exports: any;
}

declare module 'npm/lib/search/format-package-stream' {
  declare module.exports: any;
}

declare module 'npm/lib/search/package-filter' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/ansi-trim' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/audit-error' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/cmd-list' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-deep' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-shallow' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/definition' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/definitions' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/describe-all' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config/flatten' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/config' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/deref-command' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/did-you-mean' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/display' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/error-message' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/exit-handler' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/explain-dep' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/explain-eresolve' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/file-exists' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/format-bytes' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/get-identity' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/hosted-git-info-from-manifest' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows-bash' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows-shell' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/log-file' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/log-shim' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/npm-usage' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/open-url' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/otplease' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/path' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/ping' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/pulse-till-done' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/queryable' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-package-name' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-user-info' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/reify-finish' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/reify-output' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/replace-info' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/split-package-names' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/tar' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/timers' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/unsupported' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/update-notifier' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/usage' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/with-chown-sync' {
  declare module.exports: any;
}

declare module 'npm/lib/workspaces/get-workspaces' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm/bin/npm-cli.js' {
  declare module.exports: $Exports<'npm/bin/npm-cli'>;
}
declare module 'npm/bin/npx-cli.js' {
  declare module.exports: $Exports<'npm/bin/npx-cli'>;
}
declare module 'npm/index' {
  declare module.exports: $Exports<'npm'>;
}
declare module 'npm/index.js' {
  declare module.exports: $Exports<'npm'>;
}
declare module 'npm/lib/arborist-cmd.js' {
  declare module.exports: $Exports<'npm/lib/arborist-cmd'>;
}
declare module 'npm/lib/auth/legacy.js' {
  declare module.exports: $Exports<'npm/lib/auth/legacy'>;
}
declare module 'npm/lib/auth/oauth.js' {
  declare module.exports: $Exports<'npm/lib/auth/oauth'>;
}
declare module 'npm/lib/auth/saml.js' {
  declare module.exports: $Exports<'npm/lib/auth/saml'>;
}
declare module 'npm/lib/auth/sso.js' {
  declare module.exports: $Exports<'npm/lib/auth/sso'>;
}
declare module 'npm/lib/base-command.js' {
  declare module.exports: $Exports<'npm/lib/base-command'>;
}
declare module 'npm/lib/cli.js' {
  declare module.exports: $Exports<'npm/lib/cli'>;
}
declare module 'npm/lib/commands/access.js' {
  declare module.exports: $Exports<'npm/lib/commands/access'>;
}
declare module 'npm/lib/commands/adduser.js' {
  declare module.exports: $Exports<'npm/lib/commands/adduser'>;
}
declare module 'npm/lib/commands/audit.js' {
  declare module.exports: $Exports<'npm/lib/commands/audit'>;
}
declare module 'npm/lib/commands/bin.js' {
  declare module.exports: $Exports<'npm/lib/commands/bin'>;
}
declare module 'npm/lib/commands/birthday.js' {
  declare module.exports: $Exports<'npm/lib/commands/birthday'>;
}
declare module 'npm/lib/commands/bugs.js' {
  declare module.exports: $Exports<'npm/lib/commands/bugs'>;
}
declare module 'npm/lib/commands/cache.js' {
  declare module.exports: $Exports<'npm/lib/commands/cache'>;
}
declare module 'npm/lib/commands/ci.js' {
  declare module.exports: $Exports<'npm/lib/commands/ci'>;
}
declare module 'npm/lib/commands/completion.js' {
  declare module.exports: $Exports<'npm/lib/commands/completion'>;
}
declare module 'npm/lib/commands/config.js' {
  declare module.exports: $Exports<'npm/lib/commands/config'>;
}
declare module 'npm/lib/commands/dedupe.js' {
  declare module.exports: $Exports<'npm/lib/commands/dedupe'>;
}
declare module 'npm/lib/commands/deprecate.js' {
  declare module.exports: $Exports<'npm/lib/commands/deprecate'>;
}
declare module 'npm/lib/commands/diff.js' {
  declare module.exports: $Exports<'npm/lib/commands/diff'>;
}
declare module 'npm/lib/commands/dist-tag.js' {
  declare module.exports: $Exports<'npm/lib/commands/dist-tag'>;
}
declare module 'npm/lib/commands/docs.js' {
  declare module.exports: $Exports<'npm/lib/commands/docs'>;
}
declare module 'npm/lib/commands/doctor.js' {
  declare module.exports: $Exports<'npm/lib/commands/doctor'>;
}
declare module 'npm/lib/commands/edit.js' {
  declare module.exports: $Exports<'npm/lib/commands/edit'>;
}
declare module 'npm/lib/commands/exec.js' {
  declare module.exports: $Exports<'npm/lib/commands/exec'>;
}
declare module 'npm/lib/commands/explain.js' {
  declare module.exports: $Exports<'npm/lib/commands/explain'>;
}
declare module 'npm/lib/commands/explore.js' {
  declare module.exports: $Exports<'npm/lib/commands/explore'>;
}
declare module 'npm/lib/commands/find-dupes.js' {
  declare module.exports: $Exports<'npm/lib/commands/find-dupes'>;
}
declare module 'npm/lib/commands/fund.js' {
  declare module.exports: $Exports<'npm/lib/commands/fund'>;
}
declare module 'npm/lib/commands/get.js' {
  declare module.exports: $Exports<'npm/lib/commands/get'>;
}
declare module 'npm/lib/commands/help-search.js' {
  declare module.exports: $Exports<'npm/lib/commands/help-search'>;
}
declare module 'npm/lib/commands/help.js' {
  declare module.exports: $Exports<'npm/lib/commands/help'>;
}
declare module 'npm/lib/commands/hook.js' {
  declare module.exports: $Exports<'npm/lib/commands/hook'>;
}
declare module 'npm/lib/commands/init.js' {
  declare module.exports: $Exports<'npm/lib/commands/init'>;
}
declare module 'npm/lib/commands/install-ci-test.js' {
  declare module.exports: $Exports<'npm/lib/commands/install-ci-test'>;
}
declare module 'npm/lib/commands/install-test.js' {
  declare module.exports: $Exports<'npm/lib/commands/install-test'>;
}
declare module 'npm/lib/commands/install.js' {
  declare module.exports: $Exports<'npm/lib/commands/install'>;
}
declare module 'npm/lib/commands/link.js' {
  declare module.exports: $Exports<'npm/lib/commands/link'>;
}
declare module 'npm/lib/commands/ll.js' {
  declare module.exports: $Exports<'npm/lib/commands/ll'>;
}
declare module 'npm/lib/commands/logout.js' {
  declare module.exports: $Exports<'npm/lib/commands/logout'>;
}
declare module 'npm/lib/commands/ls.js' {
  declare module.exports: $Exports<'npm/lib/commands/ls'>;
}
declare module 'npm/lib/commands/org.js' {
  declare module.exports: $Exports<'npm/lib/commands/org'>;
}
declare module 'npm/lib/commands/outdated.js' {
  declare module.exports: $Exports<'npm/lib/commands/outdated'>;
}
declare module 'npm/lib/commands/owner.js' {
  declare module.exports: $Exports<'npm/lib/commands/owner'>;
}
declare module 'npm/lib/commands/pack.js' {
  declare module.exports: $Exports<'npm/lib/commands/pack'>;
}
declare module 'npm/lib/commands/ping.js' {
  declare module.exports: $Exports<'npm/lib/commands/ping'>;
}
declare module 'npm/lib/commands/pkg.js' {
  declare module.exports: $Exports<'npm/lib/commands/pkg'>;
}
declare module 'npm/lib/commands/prefix.js' {
  declare module.exports: $Exports<'npm/lib/commands/prefix'>;
}
declare module 'npm/lib/commands/profile.js' {
  declare module.exports: $Exports<'npm/lib/commands/profile'>;
}
declare module 'npm/lib/commands/prune.js' {
  declare module.exports: $Exports<'npm/lib/commands/prune'>;
}
declare module 'npm/lib/commands/publish.js' {
  declare module.exports: $Exports<'npm/lib/commands/publish'>;
}
declare module 'npm/lib/commands/rebuild.js' {
  declare module.exports: $Exports<'npm/lib/commands/rebuild'>;
}
declare module 'npm/lib/commands/repo.js' {
  declare module.exports: $Exports<'npm/lib/commands/repo'>;
}
declare module 'npm/lib/commands/restart.js' {
  declare module.exports: $Exports<'npm/lib/commands/restart'>;
}
declare module 'npm/lib/commands/root.js' {
  declare module.exports: $Exports<'npm/lib/commands/root'>;
}
declare module 'npm/lib/commands/run-script.js' {
  declare module.exports: $Exports<'npm/lib/commands/run-script'>;
}
declare module 'npm/lib/commands/search.js' {
  declare module.exports: $Exports<'npm/lib/commands/search'>;
}
declare module 'npm/lib/commands/set-script.js' {
  declare module.exports: $Exports<'npm/lib/commands/set-script'>;
}
declare module 'npm/lib/commands/set.js' {
  declare module.exports: $Exports<'npm/lib/commands/set'>;
}
declare module 'npm/lib/commands/shrinkwrap.js' {
  declare module.exports: $Exports<'npm/lib/commands/shrinkwrap'>;
}
declare module 'npm/lib/commands/star.js' {
  declare module.exports: $Exports<'npm/lib/commands/star'>;
}
declare module 'npm/lib/commands/stars.js' {
  declare module.exports: $Exports<'npm/lib/commands/stars'>;
}
declare module 'npm/lib/commands/start.js' {
  declare module.exports: $Exports<'npm/lib/commands/start'>;
}
declare module 'npm/lib/commands/stop.js' {
  declare module.exports: $Exports<'npm/lib/commands/stop'>;
}
declare module 'npm/lib/commands/team.js' {
  declare module.exports: $Exports<'npm/lib/commands/team'>;
}
declare module 'npm/lib/commands/test.js' {
  declare module.exports: $Exports<'npm/lib/commands/test'>;
}
declare module 'npm/lib/commands/token.js' {
  declare module.exports: $Exports<'npm/lib/commands/token'>;
}
declare module 'npm/lib/commands/uninstall.js' {
  declare module.exports: $Exports<'npm/lib/commands/uninstall'>;
}
declare module 'npm/lib/commands/unpublish.js' {
  declare module.exports: $Exports<'npm/lib/commands/unpublish'>;
}
declare module 'npm/lib/commands/unstar.js' {
  declare module.exports: $Exports<'npm/lib/commands/unstar'>;
}
declare module 'npm/lib/commands/update.js' {
  declare module.exports: $Exports<'npm/lib/commands/update'>;
}
declare module 'npm/lib/commands/version.js' {
  declare module.exports: $Exports<'npm/lib/commands/version'>;
}
declare module 'npm/lib/commands/view.js' {
  declare module.exports: $Exports<'npm/lib/commands/view'>;
}
declare module 'npm/lib/commands/whoami.js' {
  declare module.exports: $Exports<'npm/lib/commands/whoami'>;
}
declare module 'npm/lib/exec/get-workspace-location-msg.js' {
  declare module.exports: $Exports<'npm/lib/exec/get-workspace-location-msg'>;
}
declare module 'npm/lib/lifecycle-cmd.js' {
  declare module.exports: $Exports<'npm/lib/lifecycle-cmd'>;
}
declare module 'npm/lib/npm.js' {
  declare module.exports: $Exports<'npm/lib/npm'>;
}
declare module 'npm/lib/search/format-package-stream.js' {
  declare module.exports: $Exports<'npm/lib/search/format-package-stream'>;
}
declare module 'npm/lib/search/package-filter.js' {
  declare module.exports: $Exports<'npm/lib/search/package-filter'>;
}
declare module 'npm/lib/utils/ansi-trim.js' {
  declare module.exports: $Exports<'npm/lib/utils/ansi-trim'>;
}
declare module 'npm/lib/utils/audit-error.js' {
  declare module.exports: $Exports<'npm/lib/utils/audit-error'>;
}
declare module 'npm/lib/utils/cmd-list.js' {
  declare module.exports: $Exports<'npm/lib/utils/cmd-list'>;
}
declare module 'npm/lib/utils/completion/installed-deep.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-deep'>;
}
declare module 'npm/lib/utils/completion/installed-shallow.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-shallow'>;
}
declare module 'npm/lib/utils/config/definition.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/definition'>;
}
declare module 'npm/lib/utils/config/definitions.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/definitions'>;
}
declare module 'npm/lib/utils/config/describe-all.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/describe-all'>;
}
declare module 'npm/lib/utils/config/flatten.js' {
  declare module.exports: $Exports<'npm/lib/utils/config/flatten'>;
}
declare module 'npm/lib/utils/config/index' {
  declare module.exports: $Exports<'npm/lib/utils/config'>;
}
declare module 'npm/lib/utils/config/index.js' {
  declare module.exports: $Exports<'npm/lib/utils/config'>;
}
declare module 'npm/lib/utils/deref-command.js' {
  declare module.exports: $Exports<'npm/lib/utils/deref-command'>;
}
declare module 'npm/lib/utils/did-you-mean.js' {
  declare module.exports: $Exports<'npm/lib/utils/did-you-mean'>;
}
declare module 'npm/lib/utils/display.js' {
  declare module.exports: $Exports<'npm/lib/utils/display'>;
}
declare module 'npm/lib/utils/error-message.js' {
  declare module.exports: $Exports<'npm/lib/utils/error-message'>;
}
declare module 'npm/lib/utils/exit-handler.js' {
  declare module.exports: $Exports<'npm/lib/utils/exit-handler'>;
}
declare module 'npm/lib/utils/explain-dep.js' {
  declare module.exports: $Exports<'npm/lib/utils/explain-dep'>;
}
declare module 'npm/lib/utils/explain-eresolve.js' {
  declare module.exports: $Exports<'npm/lib/utils/explain-eresolve'>;
}
declare module 'npm/lib/utils/file-exists.js' {
  declare module.exports: $Exports<'npm/lib/utils/file-exists'>;
}
declare module 'npm/lib/utils/format-bytes.js' {
  declare module.exports: $Exports<'npm/lib/utils/format-bytes'>;
}
declare module 'npm/lib/utils/get-identity.js' {
  declare module.exports: $Exports<'npm/lib/utils/get-identity'>;
}
declare module 'npm/lib/utils/hosted-git-info-from-manifest.js' {
  declare module.exports: $Exports<'npm/lib/utils/hosted-git-info-from-manifest'>;
}
declare module 'npm/lib/utils/is-windows-bash.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows-bash'>;
}
declare module 'npm/lib/utils/is-windows-shell.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows-shell'>;
}
declare module 'npm/lib/utils/is-windows.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows'>;
}
declare module 'npm/lib/utils/log-file.js' {
  declare module.exports: $Exports<'npm/lib/utils/log-file'>;
}
declare module 'npm/lib/utils/log-shim.js' {
  declare module.exports: $Exports<'npm/lib/utils/log-shim'>;
}
declare module 'npm/lib/utils/npm-usage.js' {
  declare module.exports: $Exports<'npm/lib/utils/npm-usage'>;
}
declare module 'npm/lib/utils/open-url.js' {
  declare module.exports: $Exports<'npm/lib/utils/open-url'>;
}
declare module 'npm/lib/utils/otplease.js' {
  declare module.exports: $Exports<'npm/lib/utils/otplease'>;
}
declare module 'npm/lib/utils/path.js' {
  declare module.exports: $Exports<'npm/lib/utils/path'>;
}
declare module 'npm/lib/utils/ping.js' {
  declare module.exports: $Exports<'npm/lib/utils/ping'>;
}
declare module 'npm/lib/utils/pulse-till-done.js' {
  declare module.exports: $Exports<'npm/lib/utils/pulse-till-done'>;
}
declare module 'npm/lib/utils/queryable.js' {
  declare module.exports: $Exports<'npm/lib/utils/queryable'>;
}
declare module 'npm/lib/utils/read-package-name.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-package-name'>;
}
declare module 'npm/lib/utils/read-user-info.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-user-info'>;
}
declare module 'npm/lib/utils/reify-finish.js' {
  declare module.exports: $Exports<'npm/lib/utils/reify-finish'>;
}
declare module 'npm/lib/utils/reify-output.js' {
  declare module.exports: $Exports<'npm/lib/utils/reify-output'>;
}
declare module 'npm/lib/utils/replace-info.js' {
  declare module.exports: $Exports<'npm/lib/utils/replace-info'>;
}
declare module 'npm/lib/utils/split-package-names.js' {
  declare module.exports: $Exports<'npm/lib/utils/split-package-names'>;
}
declare module 'npm/lib/utils/tar.js' {
  declare module.exports: $Exports<'npm/lib/utils/tar'>;
}
declare module 'npm/lib/utils/timers.js' {
  declare module.exports: $Exports<'npm/lib/utils/timers'>;
}
declare module 'npm/lib/utils/unsupported.js' {
  declare module.exports: $Exports<'npm/lib/utils/unsupported'>;
}
declare module 'npm/lib/utils/update-notifier.js' {
  declare module.exports: $Exports<'npm/lib/utils/update-notifier'>;
}
declare module 'npm/lib/utils/usage.js' {
  declare module.exports: $Exports<'npm/lib/utils/usage'>;
}
declare module 'npm/lib/utils/with-chown-sync.js' {
  declare module.exports: $Exports<'npm/lib/utils/with-chown-sync'>;
}
declare module 'npm/lib/workspaces/get-workspaces.js' {
  declare module.exports: $Exports<'npm/lib/workspaces/get-workspaces'>;
}
