// flow-typed signature: bf44f112978fc2d3968715db3cfbb124
// flow-typed version: <<STUB>>/react-date-plus-time-range_v^1.0.1/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-date-plus-time-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-date-plus-time-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-date-plus-time-range/dist/components/Calendar' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/components/DateRange' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/components/DayCell' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/components/DefinedRange' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/components/Month' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/defaultRanges' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ar' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/bg' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ca' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/cs' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/da' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/de' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/el' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/en-GB' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/en-US' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/eo' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/es' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/fi' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/fil' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/fr-CH' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/fr' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/hr' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/id' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/is' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/it' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ja' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ko' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/mk' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/nb' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/nl' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/pl' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/pt' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ro' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ru' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/sk' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/sv' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/th' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/tr' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/ua' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/vi' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/zh-CN' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/locale/zh-TW' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/styles' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/dist/utils' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/jest.config' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/postcss.config' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/setupTests' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/Calendar' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/Calendar.test' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/DateRange' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/DateRange.test' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/DayCell' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/DefinedRange' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/components/Month' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/defaultRanges' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ar' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/bg' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ca' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/cs' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/da' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/de' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/el' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/en-GB' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/en-US' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/eo' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/es' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/fi' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/fil' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/fr-CH' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/fr' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/hr' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/id' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/is' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/it' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ja' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ko' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/mk' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/nb' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/nl' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/pl' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/pt' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ro' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ru' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/sk' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/sv' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/th' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/tr' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/ua' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/vi' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/zh-CN' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/locale/zh-TW' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/styles' {
  declare module.exports: any;
}

declare module 'react-date-plus-time-range/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-date-plus-time-range/dist/components/Calendar.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/components/Calendar'>;
}
declare module 'react-date-plus-time-range/dist/components/DateRange.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/components/DateRange'>;
}
declare module 'react-date-plus-time-range/dist/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/components/DateRangePicker'>;
}
declare module 'react-date-plus-time-range/dist/components/DayCell.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/components/DayCell'>;
}
declare module 'react-date-plus-time-range/dist/components/DefinedRange.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/components/DefinedRange'>;
}
declare module 'react-date-plus-time-range/dist/components/Month.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/components/Month'>;
}
declare module 'react-date-plus-time-range/dist/defaultRanges.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/defaultRanges'>;
}
declare module 'react-date-plus-time-range/dist/index' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist'>;
}
declare module 'react-date-plus-time-range/dist/index.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist'>;
}
declare module 'react-date-plus-time-range/dist/locale/ar.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ar'>;
}
declare module 'react-date-plus-time-range/dist/locale/bg.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/bg'>;
}
declare module 'react-date-plus-time-range/dist/locale/ca.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ca'>;
}
declare module 'react-date-plus-time-range/dist/locale/cs.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/cs'>;
}
declare module 'react-date-plus-time-range/dist/locale/da.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/da'>;
}
declare module 'react-date-plus-time-range/dist/locale/de.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/de'>;
}
declare module 'react-date-plus-time-range/dist/locale/el.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/el'>;
}
declare module 'react-date-plus-time-range/dist/locale/en-GB.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/en-GB'>;
}
declare module 'react-date-plus-time-range/dist/locale/en-US.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/en-US'>;
}
declare module 'react-date-plus-time-range/dist/locale/eo.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/eo'>;
}
declare module 'react-date-plus-time-range/dist/locale/es.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/es'>;
}
declare module 'react-date-plus-time-range/dist/locale/fi.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/fi'>;
}
declare module 'react-date-plus-time-range/dist/locale/fil.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/fil'>;
}
declare module 'react-date-plus-time-range/dist/locale/fr-CH.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/fr-CH'>;
}
declare module 'react-date-plus-time-range/dist/locale/fr.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/fr'>;
}
declare module 'react-date-plus-time-range/dist/locale/hr.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/hr'>;
}
declare module 'react-date-plus-time-range/dist/locale/id.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/id'>;
}
declare module 'react-date-plus-time-range/dist/locale/index' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale'>;
}
declare module 'react-date-plus-time-range/dist/locale/index.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale'>;
}
declare module 'react-date-plus-time-range/dist/locale/is.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/is'>;
}
declare module 'react-date-plus-time-range/dist/locale/it.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/it'>;
}
declare module 'react-date-plus-time-range/dist/locale/ja.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ja'>;
}
declare module 'react-date-plus-time-range/dist/locale/ko.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ko'>;
}
declare module 'react-date-plus-time-range/dist/locale/mk.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/mk'>;
}
declare module 'react-date-plus-time-range/dist/locale/nb.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/nb'>;
}
declare module 'react-date-plus-time-range/dist/locale/nl.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/nl'>;
}
declare module 'react-date-plus-time-range/dist/locale/pl.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/pl'>;
}
declare module 'react-date-plus-time-range/dist/locale/pt.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/pt'>;
}
declare module 'react-date-plus-time-range/dist/locale/ro.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ro'>;
}
declare module 'react-date-plus-time-range/dist/locale/ru.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ru'>;
}
declare module 'react-date-plus-time-range/dist/locale/sk.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/sk'>;
}
declare module 'react-date-plus-time-range/dist/locale/sv.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/sv'>;
}
declare module 'react-date-plus-time-range/dist/locale/th.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/th'>;
}
declare module 'react-date-plus-time-range/dist/locale/tr.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/tr'>;
}
declare module 'react-date-plus-time-range/dist/locale/ua.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/ua'>;
}
declare module 'react-date-plus-time-range/dist/locale/vi.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/vi'>;
}
declare module 'react-date-plus-time-range/dist/locale/zh-CN.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/zh-CN'>;
}
declare module 'react-date-plus-time-range/dist/locale/zh-TW.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/locale/zh-TW'>;
}
declare module 'react-date-plus-time-range/dist/styles.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/styles'>;
}
declare module 'react-date-plus-time-range/dist/utils.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/dist/utils'>;
}
declare module 'react-date-plus-time-range/jest.config.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/jest.config'>;
}
declare module 'react-date-plus-time-range/postcss.config.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/postcss.config'>;
}
declare module 'react-date-plus-time-range/setupTests.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/setupTests'>;
}
declare module 'react-date-plus-time-range/src/components/Calendar.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/Calendar'>;
}
declare module 'react-date-plus-time-range/src/components/Calendar.test.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/Calendar.test'>;
}
declare module 'react-date-plus-time-range/src/components/DateRange.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/DateRange'>;
}
declare module 'react-date-plus-time-range/src/components/DateRange.test.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/DateRange.test'>;
}
declare module 'react-date-plus-time-range/src/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/DateRangePicker'>;
}
declare module 'react-date-plus-time-range/src/components/DayCell.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/DayCell'>;
}
declare module 'react-date-plus-time-range/src/components/DefinedRange.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/DefinedRange'>;
}
declare module 'react-date-plus-time-range/src/components/Month.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/components/Month'>;
}
declare module 'react-date-plus-time-range/src/defaultRanges.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/defaultRanges'>;
}
declare module 'react-date-plus-time-range/src/index' {
  declare module.exports: $Exports<'react-date-plus-time-range/src'>;
}
declare module 'react-date-plus-time-range/src/index.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src'>;
}
declare module 'react-date-plus-time-range/src/locale/ar.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ar'>;
}
declare module 'react-date-plus-time-range/src/locale/bg.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/bg'>;
}
declare module 'react-date-plus-time-range/src/locale/ca.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ca'>;
}
declare module 'react-date-plus-time-range/src/locale/cs.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/cs'>;
}
declare module 'react-date-plus-time-range/src/locale/da.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/da'>;
}
declare module 'react-date-plus-time-range/src/locale/de.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/de'>;
}
declare module 'react-date-plus-time-range/src/locale/el.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/el'>;
}
declare module 'react-date-plus-time-range/src/locale/en-GB.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/en-GB'>;
}
declare module 'react-date-plus-time-range/src/locale/en-US.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/en-US'>;
}
declare module 'react-date-plus-time-range/src/locale/eo.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/eo'>;
}
declare module 'react-date-plus-time-range/src/locale/es.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/es'>;
}
declare module 'react-date-plus-time-range/src/locale/fi.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/fi'>;
}
declare module 'react-date-plus-time-range/src/locale/fil.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/fil'>;
}
declare module 'react-date-plus-time-range/src/locale/fr-CH.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/fr-CH'>;
}
declare module 'react-date-plus-time-range/src/locale/fr.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/fr'>;
}
declare module 'react-date-plus-time-range/src/locale/hr.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/hr'>;
}
declare module 'react-date-plus-time-range/src/locale/id.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/id'>;
}
declare module 'react-date-plus-time-range/src/locale/index' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale'>;
}
declare module 'react-date-plus-time-range/src/locale/index.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale'>;
}
declare module 'react-date-plus-time-range/src/locale/is.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/is'>;
}
declare module 'react-date-plus-time-range/src/locale/it.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/it'>;
}
declare module 'react-date-plus-time-range/src/locale/ja.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ja'>;
}
declare module 'react-date-plus-time-range/src/locale/ko.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ko'>;
}
declare module 'react-date-plus-time-range/src/locale/mk.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/mk'>;
}
declare module 'react-date-plus-time-range/src/locale/nb.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/nb'>;
}
declare module 'react-date-plus-time-range/src/locale/nl.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/nl'>;
}
declare module 'react-date-plus-time-range/src/locale/pl.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/pl'>;
}
declare module 'react-date-plus-time-range/src/locale/pt.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/pt'>;
}
declare module 'react-date-plus-time-range/src/locale/ro.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ro'>;
}
declare module 'react-date-plus-time-range/src/locale/ru.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ru'>;
}
declare module 'react-date-plus-time-range/src/locale/sk.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/sk'>;
}
declare module 'react-date-plus-time-range/src/locale/sv.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/sv'>;
}
declare module 'react-date-plus-time-range/src/locale/th.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/th'>;
}
declare module 'react-date-plus-time-range/src/locale/tr.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/tr'>;
}
declare module 'react-date-plus-time-range/src/locale/ua.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/ua'>;
}
declare module 'react-date-plus-time-range/src/locale/vi.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/vi'>;
}
declare module 'react-date-plus-time-range/src/locale/zh-CN.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/zh-CN'>;
}
declare module 'react-date-plus-time-range/src/locale/zh-TW.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/locale/zh-TW'>;
}
declare module 'react-date-plus-time-range/src/styles.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/styles'>;
}
declare module 'react-date-plus-time-range/src/utils.js' {
  declare module.exports: $Exports<'react-date-plus-time-range/src/utils'>;
}
