// flow-typed signature: 7e56845b4e366d9660f3923022ffb29e
// flow-typed version: <<STUB>>/react-router-scroll-top_v^0.2.1/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-scroll-top'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-scroll-top' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-scroll-top/dist/react-router-scroll-top.cjs' {
  declare module.exports: any;
}

declare module 'react-router-scroll-top/dist/react-router-scroll-top.esm' {
  declare module.exports: any;
}

declare module 'react-router-scroll-top/dist/react-router-scroll-top.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-scroll-top/dist/react-router-scroll-top.cjs.js' {
  declare module.exports: $Exports<'react-router-scroll-top/dist/react-router-scroll-top.cjs'>;
}
declare module 'react-router-scroll-top/dist/react-router-scroll-top.esm.js' {
  declare module.exports: $Exports<'react-router-scroll-top/dist/react-router-scroll-top.esm'>;
}
declare module 'react-router-scroll-top/dist/react-router-scroll-top.umd.js' {
  declare module.exports: $Exports<'react-router-scroll-top/dist/react-router-scroll-top.umd'>;
}
