// flow-typed signature: d748178b814fbd449d962dc85462aa1a
// flow-typed version: <<STUB>>/react-responsive-sidebar_v^0.1.16/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-sidebar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-sidebar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-sidebar/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-sidebar/dist/bundle.js' {
  declare module.exports: $Exports<'react-responsive-sidebar/dist/bundle'>;
}
declare module 'react-responsive-sidebar/index' {
  declare module.exports: $Exports<'react-responsive-sidebar'>;
}
declare module 'react-responsive-sidebar/index.js' {
  declare module.exports: $Exports<'react-responsive-sidebar'>;
}
