// flow-typed signature: 483eb0e6115d27ac38de39ca3829298a
// flow-typed version: <<STUB>>/react-hook-form_v^5.7.2/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hook-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hook-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hook-form/dist/react-hook-form.es' {
  declare module.exports: any;
}

declare module 'react-hook-form/dist/react-hook-form.ie11' {
  declare module.exports: any;
}

declare module 'react-hook-form/dist/react-hook-form' {
  declare module.exports: any;
}

declare module 'react-hook-form/dist/react-hook-form.min.es' {
  declare module.exports: any;
}

declare module 'react-hook-form/dist/react-hook-form.umd' {
  declare module.exports: any;
}

declare module 'react-hook-form/rollup/rollup.umd.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hook-form/dist/react-hook-form.es.js' {
  declare module.exports: $Exports<'react-hook-form/dist/react-hook-form.es'>;
}
declare module 'react-hook-form/dist/react-hook-form.ie11.js' {
  declare module.exports: $Exports<'react-hook-form/dist/react-hook-form.ie11'>;
}
declare module 'react-hook-form/dist/react-hook-form.js' {
  declare module.exports: $Exports<'react-hook-form/dist/react-hook-form'>;
}
declare module 'react-hook-form/dist/react-hook-form.min.es.js' {
  declare module.exports: $Exports<'react-hook-form/dist/react-hook-form.min.es'>;
}
declare module 'react-hook-form/dist/react-hook-form.umd.js' {
  declare module.exports: $Exports<'react-hook-form/dist/react-hook-form.umd'>;
}
declare module 'react-hook-form/rollup/rollup.umd.config.js' {
  declare module.exports: $Exports<'react-hook-form/rollup/rollup.umd.config'>;
}
