// flow-typed signature: 10609c9baa8d99b2ff74e83252b5d1ed
// flow-typed version: <<STUB>>/react-minimal-pie-chart_v^7.3.1/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-minimal-pie-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-minimal-pie-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-minimal-pie-chart/dist' {
  declare module.exports: any;
}

declare module 'react-minimal-pie-chart/es' {
  declare module.exports: any;
}

declare module 'react-minimal-pie-chart/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-minimal-pie-chart/dist/index' {
  declare module.exports: $Exports<'react-minimal-pie-chart/dist'>;
}
declare module 'react-minimal-pie-chart/dist/index.js' {
  declare module.exports: $Exports<'react-minimal-pie-chart/dist'>;
}
declare module 'react-minimal-pie-chart/es/index' {
  declare module.exports: $Exports<'react-minimal-pie-chart/es'>;
}
declare module 'react-minimal-pie-chart/es/index.js' {
  declare module.exports: $Exports<'react-minimal-pie-chart/es'>;
}
declare module 'react-minimal-pie-chart/lib/index' {
  declare module.exports: $Exports<'react-minimal-pie-chart/lib'>;
}
declare module 'react-minimal-pie-chart/lib/index.js' {
  declare module.exports: $Exports<'react-minimal-pie-chart/lib'>;
}
