// flow-typed signature: 3dac2e1752f1c5d8c51ff3a890084bc9
// flow-typed version: <<STUB>>/react-google-charts_v^3.0.15/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-charts/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-google-charts/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-google-charts/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-charts/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-google-charts/dist/index.cjs'>;
}
declare module 'react-google-charts/dist/index.esm.js' {
  declare module.exports: $Exports<'react-google-charts/dist/index.esm'>;
}
declare module 'react-google-charts/dist/index.umd.js' {
  declare module.exports: $Exports<'react-google-charts/dist/index.umd'>;
}
