// flow-typed signature: 80e1a556a1300d4aa85f0a3457194c4e
// flow-typed version: <<STUB>>/turf-multipoint_v^1.0.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'turf-multipoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'turf-multipoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'turf-multipoint/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'turf-multipoint/index' {
  declare module.exports: $Exports<'turf-multipoint'>;
}
declare module 'turf-multipoint/index.js' {
  declare module.exports: $Exports<'turf-multipoint'>;
}
declare module 'turf-multipoint/test.js' {
  declare module.exports: $Exports<'turf-multipoint/test'>;
}
