// flow-typed signature: 8bc56de3fcd17fc8d6baf2c77445329c
// flow-typed version: <<STUB>>/use-deep-compare-effect_v^1.3.1/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'use-deep-compare-effect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'use-deep-compare-effect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.cjs' {
  declare module.exports: any;
}

declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.esm' {
  declare module.exports: any;
}

declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.umd' {
  declare module.exports: any;
}

declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.cjs.js' {
  declare module.exports: $Exports<'use-deep-compare-effect/dist/use-deep-compare-effect.cjs'>;
}
declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.esm.js' {
  declare module.exports: $Exports<'use-deep-compare-effect/dist/use-deep-compare-effect.esm'>;
}
declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.umd.js' {
  declare module.exports: $Exports<'use-deep-compare-effect/dist/use-deep-compare-effect.umd'>;
}
declare module 'use-deep-compare-effect/dist/use-deep-compare-effect.umd.min.js' {
  declare module.exports: $Exports<'use-deep-compare-effect/dist/use-deep-compare-effect.umd.min'>;
}
