// flow-typed signature: d419ffdad58818d26573660a52fdf696
// flow-typed version: <<STUB>>/@ckeditor/ckeditor5-build-classic_v^19.0.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ckeditor/ckeditor5-build-classic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ckeditor/ckeditor5-build-classic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ckeditor/ckeditor5-build-classic/build/ckeditor' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/af' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ar' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ast' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/az' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/bg' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ca' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/cs' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/da' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/de-ch' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/de' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/el' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/en-au' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/en-gb' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/eo' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/es' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/et' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/eu' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/fa' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/fi' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/fr' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/gl' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/gu' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/he' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/hr' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/hu' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/id' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/it' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ja' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/km' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/kn' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ko' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ku' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/lt' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/lv' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ms' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/nb' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ne' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/nl' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/no' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/oc' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/pl' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/pt-br' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/pt' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ro' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ru' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/si' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/sk' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/sl' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/sq' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/sr-latn' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/sr' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/sv' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/th' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/tr' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/tt' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/ug' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/uk' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/vi' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/zh-cn' {
  declare module.exports: any;
}

declare module '@ckeditor/ckeditor5-build-classic/build/translations/zh' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ckeditor/ckeditor5-build-classic/build/ckeditor.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/ckeditor'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/af.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/af'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ar.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ar'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ast.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ast'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/az.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/az'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/bg.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/bg'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ca.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ca'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/cs.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/cs'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/da.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/da'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/de-ch.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/de-ch'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/de.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/de'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/el.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/el'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/en-au.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/en-au'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/en-gb.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/en-gb'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/eo.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/eo'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/es.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/es'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/et.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/et'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/eu.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/eu'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/fa.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/fa'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/fi.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/fi'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/fr.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/fr'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/gl.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/gl'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/gu.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/gu'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/he.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/he'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/hr.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/hr'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/hu.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/hu'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/id.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/id'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/it.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/it'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ja.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ja'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/km.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/km'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/kn.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/kn'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ko.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ko'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ku.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ku'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/lt.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/lt'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/lv.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/lv'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ms.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ms'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/nb.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/nb'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ne.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ne'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/nl.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/nl'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/no.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/no'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/oc.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/oc'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/pl.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/pl'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/pt-br.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/pt-br'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/pt.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/pt'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ro.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ro'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ru.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ru'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/si.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/si'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/sk.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/sk'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/sl.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/sl'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/sq.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/sq'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/sr-latn.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/sr-latn'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/sr.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/sr'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/sv.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/sv'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/th.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/th'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/tr.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/tr'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/tt.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/tt'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/ug.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/ug'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/uk.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/uk'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/vi.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/vi'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/zh-cn.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/zh-cn'>;
}
declare module '@ckeditor/ckeditor5-build-classic/build/translations/zh.js' {
  declare module.exports: $Exports<'@ckeditor/ckeditor5-build-classic/build/translations/zh'>;
}
