export const Endpoints = {
  Inventory: '/inventory',
  GetInventory: '/getInventory/:idStore',
  InsertInventory: '/insertInventory',
  Sales: '/sales',
  GetSales: '/getSales/:idStore',
  GetSaleDetails: '/getSaleDetail/:id',
  NewSale: '/insertSale',
  Transfers: '/transfers',
  GetTransfers: '/getTransfer/:idStore',
  InsertTransfer: '/insertTransfer',
  Roles: 'lists/roles',
  Dashboard: 'dashboard',
  Colors: 'lists/getColors',
  Stores: 'lists/getStore',
  GetTypes: 'lists/getTypes',
  Characteristics: 'lists/getCharacteristics',
  Provider: 'lists/getProviders',
  Sizes: 'lists/getSizes',
  Genders: 'lists/getGenders',
  Users: 'lists/getUsers',
  PaymentMethods: 'lists/getPaymentMethods',
  Login: '/login',
  RegisterUser: '/registerUser',
  GetRoles: 'lists/getRoles',
  GetDayIncome: 'lists/getDayIncome'
};
