const Contents = {
  English: {
    pageTitle: 'INVENTORY',
    defaultSubtitle: 'Maybe you should try again.',
    labCode: 'Code',
    labColor: 'Color',
    labSize: 'Size',
    labPieces: 'Pieces',
    labPrice: 'Price',
    labGender: 'Gender',
    labType: 'Type',
    labReserved: 'Reserved',
    labStock: 'Stock',
    labInventory: 'INVENTORY',
    addNewProduct: 'New',
    Girl: 'Girl',
    Boy: 'Boy',
    minSalePrice: 'Min Sale Price',
    minCost: 'Minimun cost',
    maxSalePrice: 'Max Sale Price',
    maxCost: 'Maximum Cost'
  },
  Spanish: {
    pageTitle: 'INVENTARIO',
    defaultSubtitle: '¡No pudimos encontrar lo que buscaba! Quizás deberías intentarlo de nuevo.',
    labCode: 'Código',
    labColor: 'Color',
    labSize: 'Talla',
    labPieces: 'Piezas',
    labPrice: 'Precio',
    labGender: 'Género',
    labType: 'Tipo',
    labReserved: 'Apartados',
    labStock: 'Stock',
    labInventory: 'INVENTARIO',
    addNewProduct: 'Entrada',
    Girl: 'Niña',
    Boy: 'Niño',
    minSalePrice: 'Precio de venta minimo',
    minCost: 'Costo mínimo',
    maxSalePrice: 'Max Sale Price',
    maxCost: 'Maximum Cost'
  }
};
export default Contents;
