const Contents = {
  English: {
    pageTitle: 'INVENTORY',
    defaultSubtitle: 'Maybe you should try again.',
    lblIdProduct: 'Id',
    lblIdInventory: '# Registro',
    labCode: 'Product Code',
    labColor: 'Color',
    labSize: 'Size',
    labPieces: '# Pieces',
    labPrice: 'Price',
    labGender: 'Gender',
    labType: 'Type',
    labReserved: 'Reserved',
    labStock: 'Stock',
    labInventory: 'Inventory',
    labMaterials: 'Materials',
    feedInventory: 'Feed',
    Girl: 'Girl',
    Boy: 'Boy',
    minSalePrice: 'Min Sale Price',
    minCost: 'Minimun cost',
    maxSalePrice: 'Max Sale Price',
    maxCost: 'Maximum Cost',
    labName: 'Name / Model',
    labStatus: 'Status',
    labStore: 'Location / Store',
    labObservations: 'Observations',
    labIsExistencyVerified: 'Existency Verified'
  },
  Spanish: {
    pageTitle: 'INVENTARIOS',
    defaultSubtitle:
      '¡No pudimos encontrar lo que buscaba! Quizás deberías intentarlo de nuevo.',
    lblIdProduct: 'Id',
    lblIdInventory: '# Registro',
    labCode: 'Código de Producto',
    labColor: 'Color',
    labSize: 'Talla',
    labPieces: '# Partes',
    labPrice: 'Precio',
    labGender: 'Género',
    labType: 'Tipo',
    labReserved: 'Apartados',
    labStock: 'Stock',
    labInventory: 'INVENTARIOS',
    labMaterials: 'Materiales',
    feedInventory: 'Alimentar',
    Girl: 'Niña',
    Boy: 'Niño',
    minSalePrice: 'Precio de venta minimo',
    minCost: 'Costo mínimo',
    maxSalePrice: 'Precio de venta máximo',
    maxCost: 'Costo máximo',
    labName: 'Nombre / Modelo',
    labStatus: 'Estatus',
    labStore: 'Ubicación',
    labObservations: 'Observaciones',
    labIsExistencyVerified: 'Existencia Verificada'
  }
};
export default Contents;
